language: python
python:
  - "2.7"
services:
    - redis-server
env:
  - PGVERSION=9.1
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_install: bash bin/travis-before-install.sh
script: 
  - nosetests --with-pylons=links/test-core.ini
  - coverage run --source ckanext.realtime nosetests --with-pylons=links/test-core.ini
after_success:  coveralls
