language: python
python:
  - "2.7"
services:
    - redis-server
env:
  - PGVERSION=9.1
install:
  - pip install coveralls
before_install: bash bin/travis-before-install.sh
script: 
  - rake jasmine:ci
  - nosetests  --with-coverage --cover-package=ckanext.realtime --with-pylons=links/test-core.ini
after_success:  coveralls
